//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Domain.AddressBookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfApp.Client.Models")]
    [System.SerializableAttribute()]
    public partial class ContactDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.Domain.AddressBookServiceReference.AddressDTO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.Domain.AddressBookServiceReference.AddressDTO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfApp.Client.Models")]
    [System.SerializableAttribute()]
    public partial class AddressDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.Domain.AddressBookServiceReference.StateCodeDTO StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.Domain.AddressBookServiceReference.StateCodeDTO State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateCodeDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfApp.Client.Models")]
    public enum StateCodeDTO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VA = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressBookServiceReference.IAddressBook")]
    public interface IAddressBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/AddContact", ReplyAction="http://tempuri.org/IAddressBook/AddContactResponse")]
        bool AddContact(WebApp.Domain.AddressBookServiceReference.ContactDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/AddContactTask", ReplyAction="http://tempuri.org/IAddressBook/AddContactTaskResponse")]
        bool AddContactTask(WebApp.Domain.AddressBookServiceReference.ContactDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/UpdateContact", ReplyAction="http://tempuri.org/IAddressBook/UpdateContactResponse")]
        bool UpdateContact(WebApp.Domain.AddressBookServiceReference.ContactDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/UpdateContactTask", ReplyAction="http://tempuri.org/IAddressBook/UpdateContactTaskResponse")]
        bool UpdateContactTask(WebApp.Domain.AddressBookServiceReference.ContactDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/GetContact", ReplyAction="http://tempuri.org/IAddressBook/GetContactResponse")]
        WebApp.Domain.AddressBookServiceReference.ContactDTO GetContact(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/GetContactTask", ReplyAction="http://tempuri.org/IAddressBook/GetContactTaskResponse")]
        WebApp.Domain.AddressBookServiceReference.ContactDTO GetContactTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/DeleteContactById", ReplyAction="http://tempuri.org/IAddressBook/DeleteContactByIdResponse")]
        bool DeleteContactById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/DeleteContactByIdTask", ReplyAction="http://tempuri.org/IAddressBook/DeleteContactByIdTaskResponse")]
        bool DeleteContactByIdTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/DeleteContact", ReplyAction="http://tempuri.org/IAddressBook/DeleteContactResponse")]
        bool DeleteContact(WebApp.Domain.AddressBookServiceReference.ContactDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBook/DeleteContactTask", ReplyAction="http://tempuri.org/IAddressBook/DeleteContactTaskResponse")]
        bool DeleteContactTask(WebApp.Domain.AddressBookServiceReference.ContactDTO contact);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressBookChannel : WebApp.Domain.AddressBookServiceReference.IAddressBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressBookClient : System.ServiceModel.ClientBase<WebApp.Domain.AddressBookServiceReference.IAddressBook>, WebApp.Domain.AddressBookServiceReference.IAddressBook {
        
        public AddressBookClient() {
        }
        
        public AddressBookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressBookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressBookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressBookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddContact(WebApp.Domain.AddressBookServiceReference.ContactDTO contact) {
            return base.Channel.AddContact(contact);
        }
        
        public bool AddContactTask(WebApp.Domain.AddressBookServiceReference.ContactDTO contact) {
            return base.Channel.AddContactTask(contact);
        }
        
        public bool UpdateContact(WebApp.Domain.AddressBookServiceReference.ContactDTO contact) {
            return base.Channel.UpdateContact(contact);
        }
        
        public bool UpdateContactTask(WebApp.Domain.AddressBookServiceReference.ContactDTO contact) {
            return base.Channel.UpdateContactTask(contact);
        }
        
        public WebApp.Domain.AddressBookServiceReference.ContactDTO GetContact(int id) {
            return base.Channel.GetContact(id);
        }
        
        public WebApp.Domain.AddressBookServiceReference.ContactDTO GetContactTask(int id) {
            return base.Channel.GetContactTask(id);
        }
        
        public bool DeleteContactById(int id) {
            return base.Channel.DeleteContactById(id);
        }
        
        public bool DeleteContactByIdTask(int id) {
            return base.Channel.DeleteContactByIdTask(id);
        }
        
        public bool DeleteContact(WebApp.Domain.AddressBookServiceReference.ContactDTO contact) {
            return base.Channel.DeleteContact(contact);
        }
        
        public bool DeleteContactTask(WebApp.Domain.AddressBookServiceReference.ContactDTO contact) {
            return base.Channel.DeleteContactTask(contact);
        }
    }
}
